### ISSUE TITLE
Getting Error on using Web3 in Production(Platform Web).

### ISSUE THREAD

**Issue by Roopal-dev** [saadibrahim/universal-react-app#2]
Hi , I am using web3  inside the web platform and everything working fine in the development mode but in production getting this error in the console.If I implement web3 in the independent react project it is totally working fine .Please 
help.I need to have it in the universal app.

Thanks

Error: Uncaught TypeError: Cannot assign to read only property 'exports' of object '#<Object>'
![Screenshot 2021-11-01 at 6 45 25 PM](https://user-images.githubusercontent.com/81748062/139677512-5576551f-5520-48a3-a89f-8baa42201b24.png)

**Comment by saadibrahim** [comment]
Sorry, this is beyond the scope of this tutorial. If it works in development, something tells me its to do with bundling.
